name: from_to_time_picker
description: Simple duration time range picker that enable user pick start time and end time of day in both 24h and 12h format
version: 1.2.0
homepage: https://github.com/ahmedElsarag/from_to_time_picker

environment:
  sdk: ">=2.12.0 <3.19.2"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

flutter_intl:
  enabled: true